# Generated by Django 2.2.3 on 2019-08-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'ordering': ('lname',)},
        ),
    ]
