# Generated by Django 2.2.3 on 2019-08-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
